# Change these first
owner: Androz2091 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://blog.androz2091.fr
  - name: DDPE
    url: https://ddpe.androz2091.fr
  - name: Diswho
    url: https://diswho.androz2091.fr
  - name: Umami Analytics
    url: https://analytics.androz2091.fr
  - name: Plex
    url: https://plex.androz2091.fr/web/index.html
  - name: Tautulli
    url: https://tautulli.androz2091.fr/auth/login
  - name: Sabnzbd
    url: https://sabnzbd.androz2091.fr
  - name: Radarr
    url: https://radarr.androz2091.fr
  - name: Sonarr
    url: https://sonarr.androz2091.fr
  - name: Overseerr
    url: https://overseerr.androz2091.fr
  - name: FileBrowser
    url: https://cloud.androz2091.fr
  - name: Immich
    url: https://photos.androz2091.fr
  - name: HasteServer
    url: https://haste.androz2091.fr
  - name: VaultWarden
    url: https://vault.androz2091.fr
  - name: QBittorrent
    url: https://qbt.androz2091.fr
  - name: Instaddict
    url: https://instaddict.androz2091.fr
  - name: Online Love Calc
    url: https://love-calc.androz2091.fr
  - name: Slash Commands GUI
    url: https://slash-commands-gui.androz2091.fr
  - name: ManageInvite
    url: https://manage-invite.xyz
  - name: ManageInvite API
    url: https://api.manage-invite.xyz
  - name: (stale) ManageInvite API
    url: https://dash.manage-invite.xyz
  - name: Tagger
    url: https://timetagger.androz2091.fr
  - name: Monica
    url: https://monica.androz2091.fr
  - name: Prometheus Grafana
    url: https://prometheus-grafana.androz2091.fr
  - name: Harbor
    url: https://harbor.androz2091.fr
  - name: ArgoCD
    url: https://argocd.androz2091.fr
  - name: Main website (ndd androz2091)
    url: https://androz2091.fr
  - name: Main website (ndd simonlefort.fr)
    url: https://simonlefort.fr
  - name: Main website (ndd simonlefort.ch)
    url: https://simonlefort.ch
  - name: Stirling PDF
    url: https://pdf.androz2091.fr
  - name: Flep Guessr
    url: https://flepguessr-cs214.androz2091.fr
  - name: h5ai (Servarr)
    url: https://h5ai-servarr.androz2091.fr
    expectedStatusCodes:
      - 401
  - name: Androz2091 Discord Redirection
    url: https://androz2091.fr/discord
    maxRedirects: 0
    expectedStatusCodes:
      - 302
  - name: Paperless
    url: https://documents.androz2091.fr
  - name: Dumpus (landing)
    url: https://dumpus.app
  - name: Dumpus (web client)
    url: https://web.dumpus.app
  - name: Dumpus (API)
    url: http://api.dumpus.app/health
  - name: PDFDing
    url: https://pdfding.androz2091.fr
    expectedStatusCodes:
      - 426 # actually websocket
  - name: S4S Programming website
    url: https://prog.students4students.ch
  - name: Madeam
    url: https://madeam.fr
  - name: Clem Creations
    url: https://clem-creations.com/health

status-website:
  cname: ismyserverworki.ng
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Androz k8s cluster status
  introTitle: "**Simon** - aka Androz2091 - **k8s cluster status page**"
  introMessage: This page shows the status of the services and projects hosted on my servers. All my infrastructure is open source, see my k8s cluster manifests in the navigation bar.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: K8S Cluster manifests
      href: https://github.com/Androz2091/k8s-infrastructure
