# Change these first
owner: Androz2091 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://blog.androz2091.fr
  - name: DDPE
    url: https://ddpe.androz2091.fr
  - name: Diswho
    url: https://diswho.androz2091.fr
  - name: Umami Analytics
    url: https://analytics.androz2091.fr
  - name: Plex
    url: https://plex.androz2091.fr/web/index.html
  - name: Sabnzbd
    url: https://sabnzbd.androz2091.fr
  - name: Overseerr
    url: https://overseerr.androz2091.fr
  - name: Sonarr
    url: https://sonarr.androz2091.fr
  - name: Radarr
    url: https://radarr.androz2091.fr
  - name: Bazarr
    url: https://bazarr.androz2091.fr
  - name: Jackett
    url: https://bazarr.androz2091.fr
  - name: Portainer
    url: https://portainer.androz2091.fr
  - name: Jellyfin
    url: https://jellyfin.androz2091.fr
  - name: Cloud
    url: https://cloud.androz2091.fr
  - name: DL
    url: https://dl.androz2091.fr
  - name: Peertube
    url: https://peertube.androz2091.fr
  - name: Haste
    url: https://haste.androz2091.fr
  - name: VaultWarden
    url: https://vault.androz2091.fr
  - name: Netdata (HETZ#1)
    url: https://hetz.androz2091.fr
    expectedStatusCodes:
      - 401
  - name: My GitHub Stats API
    url: https://my-gh-stats.androz2091.fr/stats/random%20username%20
  - name: QBittorrent
    url: https://qbt.androz2091.fr
  - name: Instaddict
    url: https://instaddict.androz2091.fr
  - name: Online Love Calc
    url: https://love-calc.androz2091.fr
  - name: Slash Commands GUI
    url: https://slash-commands-gui.androz2091.fr
  - name: Twittycord
    url: https://twittycord.com
  - name: ManageInvite
    url: https://manage-invite.xyz
  - name: ManageInvite API
    url: https://api.manage-invite.xyz
  - name: Tagger
    url: https://tagger.androz2091.fr
 

status-website:
  cname: ismyserverworki.ng
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Simon** - aka Androz2091 - **services status page**"
  introMessage: This page shows the status of the services and projects hosted on my servers.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
